### PR TITLE
Updated react-native-permissions and react-native package version and added s…

### PR DESCRIPTION
**Pull request by nehabluedot**
Build and test App on Android device version 11, Location permission popup should be displayed with 3 options (While In Use, Only this time and Deny)

### CODE REVIEW

**Review by poborin — APPROVED** [review]

**Comment by poborin** [comment]
@neha are you able to restore dependencies with such `package.json`? I'm getting the following errors when I do `npm install`
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: undefined@undefined
npm ERR! Found: react@16.9.0
npm ERR! node_modules/react
npm ERR!   react@"16.9.0" from the root project
npm ERR!   peer react@"^16.9.0" from bluedot-react-native@2.0.4
npm ERR!   node_modules/bluedot-react-native
npm ERR!     bluedot-react-native@"git://github.com/Bluedot-Innovation/Bluedot-React-Native-Plugin.git#dev/2.0.4" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"16.13.1" from react-native@0.63.4
npm ERR! node_modules/react-native
npm ERR!   react-native@"^0.63.3" from the root project
npm ERR!   peer react-native@">=0.59.0-rc.0 <1.0.x" from bluedot-react-native@2.0.4
npm ERR!   node_modules/bluedot-react-native
npm ERR!     bluedot-react-native@"git://github.com/Bluedot-Innovation/Bluedot-React-Native-Plugin.git#dev/2.0.4" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See /Users/poborin/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/poborin/.npm/_logs/2021-06-16T23_40_45_252Z-debug.log
```

**Review by poborin — CHANGES_REQUESTED** [review]
hmm... If I use your `package-lock.json` then `npm install` works. However, `pod update` fails with the following error:
```
[!] No podspec found for `Permission-BluetoothPeripheral` in `../node_modules/react-native-permissions/ios/BluetoothPeripheral.podspec`
```

On the other hand, if I remove package-lock.json, then the `npm install` fails.

**Comment by nehabluedot** [comment]
> hmm... If I use your `package-lock.json` then `npm install` works. However, `pod update` fails with the following error:
> 
> ```
> [!] No podspec found for `Permission-BluetoothPeripheral` in `../node_modules/react-native-permissions/ios/BluetoothPeripheral.podspec`
> ```
> 
> On the other hand, if I remove package-lock.json, then the `npm install` fails.

Npm install worked fine here as it was using package-lock.json, I haven't tested the iOS App for this change.

**Comment by nehabluedot** [comment]
> > hmm... If I use your `package-lock.json` then `npm install` works. However, `pod update` fails with the following error:
> > ```
> > [!] No podspec found for `Permission-BluetoothPeripheral` in `../node_modules/react-native-permissions/ios/BluetoothPeripheral.podspec`
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > On the other hand, if I remove package-lock.json, then the `npm install` fails.
> 
> Npm install worked fine here as it was using package-lock.json, I haven't tested the iOS App for this change.

@poborin Fixed Pod issue, check now

**Comment by poborin** [comment]
cocoapods are failing with another error now
```
[!] CocoaPods could not find compatible versions for pod "ReactCommon/jscallinvoker":
  In Podfile:
    ReactCommon/jscallinvoker (from `../node_modules/react-native/ReactCommon`)

None of your spec sources contain a spec satisfying the dependency: `ReactCommon/jscallinvoker (from `../node_modules/react-native/ReactCommon`)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.
 ```

**Comment by nehabluedot** [comment]
@poborin `pod repo update` fixed it

**Review by poborin — APPROVED** [review]
yeah, I created a ticket to update pods for the iOS app.

**Pull request merged**
